<a href="https://colab.research.google.com/github/Akisn277/Data-Science-Sheets/blob/main/Data_Science_Sheet_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
print(arr.ndim)

1


In [ ]:
arr2=np.array([arr,[6,7,8,9,10]])
print(arr2.ndim)

2


In [ ]:
array=np.arange(12,50,3)
array

array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [ ]:
array=np.arange(15,50).reshape(5,7)
print(array)
print(array.shape)

[[15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]]
(5, 7)


In [ ]:
a=np.zeros((2,4))
c=np.empty((2,3))
d=np.full((2,2), 3)
e= np.eye(3,3)
f=np.linspace(0, 10, num=4)
print(a)
print(c)
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[4.37253351e-315 0.00000000e+000 8.61882260e+183]
 [2.59050147e-144 1.16442250e-028 6.79769037e-310]]
[[3 3]
 [3 3]]


In [ ]:
e= np.eye(3,3)
f=np.identity(5)
print (e)
print (f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
